import streamlit as st
import google.generativeai as genai

# ==========================================
# 1. CORE SETUP & PLATFORM BRANDING
# ==========================================
st.set_page_config(
    page_title="NyayaSahayak | India's Free AI Legal Assistant", 
    page_icon="⚖️", 
    layout="centered"
)

try:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception:
    st.error("System is currently undergoing maintenance. Please try again later.")
    st.stop()

# ==========================================
# 2. THE FULL-SERVICE CHAMBER HEADER
# ==========================================
st.markdown("""
    <div style='text-align: center; padding: 15px;'>
        <h1 style='color: #2c3e50; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; margin-bottom: 0px;'>⚖️ NyayaSahayak</h1>
        <h4 style='color: #34495e; font-weight: 400; margin-top: 5px;'>India's Premium AI Legal Assistant</h4>
    </div>
""", unsafe_allow_html=True)

st.info("**Powered by the Chambers of Adv. Shobhit Tiwari** \nAllahabad High Court (Lucknow Bench), District Courts & Tribunals | 📞 +91 9795971160")

# Interface Language ONLY at the top
ui_lang = st.radio("Interface Language / इंटरफ़ेस भाषा:", ["English", "Hindi"], horizontal=True)

# ==========================================
# 3. MASTER TRANSLATION & DESK DICTIONARY
# ==========================================
en = {
    "tabs": ["Citizen / Public", "Legal Professional", "Partner Advocate Program"],
    "cit_desks": ["🚨 Criminal & Police", "💻 Cyber Crime & Fraud", "🏠 Property & Civil", "💼 Corporate & Money", "🏛️ Government & Employment", "🚦 General & Motor Vehicle"],
    "cit_tools": {
        "🚨 Criminal & Police": ["Police Complaint (FIR) Drafter"],
        "💻 Cyber Crime & Fraud": ["1930 Cyber Fraud Complaint", "Bank Account Unfreeze Application"],
        "🏠 Property & Civil": ["Tenancy/Rent Agreement (UP)", "Tenant Eviction Notice"],
        "💼 Corporate & Money": ["Section 138 (Cheque Bounce) Notice", "MSME Payment Recovery Notice"],
        "🏛️ Government & Employment": ["Show Cause Notice Reply"],
        "🚦 General & Motor Vehicle": ["Traffic Challan Compounding Request"]
    },
    "adv_desks": ["📝 Legal Drafting Desk", "📚 Research & Statutes"],
    "adv_tools": {
        "📝 Legal Drafting Desk": ["Bail Application Drafter", "Affidavit Drafter (Lucknow Bench)", "Writ Petition Grounds (Art. 226)"],
        "📚 Research & Statutes": ["Case Law Summarizer", "IPC to BNS Converter"]
    },
    "btn_analyze": "Analyze & Ask Clarifications 🔍", "btn_draft": "Generate Final Draft 📄", "btn_reset": "Start Over 🔄", "req": "Request Consultation"
}

hi = {
    "tabs": ["नागरिक / आम जनता", "वकील / कानूनी पेशेवर", "पार्टनर एडवोकेट प्रोग्राम"],
    "cit_desks": ["🚨 आपराधिक और पुलिस", "💻 साइबर अपराध और धोखाधड़ी", "🏠 संपत्ति और दीवानी", "💼 वाणिज्यिक और धन", "🏛️ सरकारी और रोजगार", "🚦 सामान्य और मोटर वाहन"],
    "cit_tools": {
        "🚨 आपराधिक और पुलिस": ["पुलिस शिकायत (FIR) ड्राफ्टर"],
        "💻 साइबर अपराध और धोखाधड़ी": ["1930 साइबर धोखाधड़ी शिकायत", "बैंक खाता अनफ्रीज आवेदन"],
        "🏠 संपत्ति और दीवानी": ["किरायानामा (रेंट एग्रीमेंट) - यूपी", "किरायेदार बेदखली (Eviction) नोटिस"],
        "💼 वाणिज्यिक और धन": ["धारा 138 (चेक बाउंस) नोटिस", "MSME भुगतान वसूली नोटिस"],
        "🏛️ सरकारी और रोजगार": ["कारण बताओ (Show Cause) नोटिस का जवाब"],
        "🚦 सामान्य और मोटर वाहन": ["ट्रैफिक चालान छूट/माफी आवेदन"]
    },
    "adv_desks": ["📝 कानूनी ड्राफ्टिंग डेस्क", "📚 अनुसंधान और कानून"],
    "adv_tools": {
        "📝 कानूनी ड्राफ्टिंग डेस्क": ["जमानत (Bail) आवेदन ड्राफ्टर", "हलफनामा (Affidavit) ड्राफ्टर", "रिट याचिका के आधार (Art. 226)"],
        "📚 अनुसंधान और कानून": ["अपीलीय निर्णय (Judgment) सारांश", "कानून कनवर्टर: IPC से BNS"]
    },
    "btn_analyze": "विश्लेषण करें और प्रश्न पूछें 🔍", "btn_draft": "अंतिम ड्राफ्ट तैयार करें 📄", "btn_reset": "शुरुआत से शुरू करें 🔄", "req": "परामर्श का अनुरोध करें"
}

ui = en if ui_lang == "English" else hi

# ==========================================
# 4. NAVIGATION & GLOBAL VARIABLES
# ==========================================
st.divider()
category = st.pills("Access Portal / पोर्टल एक्सेस करें:", ui["tabs"], default=ui["tabs"][0])
st.divider()

watermark = f"\n\n---\n**Important Disclaimer:** *This preliminary document was generated by NyayaSahayak AI. It does not constitute formal legal advice. For official court submissions, tribunal representation, and strategic legal execution, please consult Adv. Shobhit Tiwari at +91 9795971160.*"

# ==========================================
# 5. CITIZEN / PUBLIC TOOLS
# ==========================================
if category == ui["tabs"][0]:
    desk = st.selectbox("Select Legal Desk:", ui["cit_desks"])
    tool = st.selectbox("Select Tool:", ui["cit_tools"][desk])

    def interactive_tool(title, info_text, initial_prompt, analyze_prompt_task, draft_prompt_task):
        st.subheader(title)
        st.info(info_text, icon="ℹ️")
        
        step_key = f"{title}_step"
        qs_key = f"{title}_qs"
        story_key = f"{title}_story"
        
        if step_key not in st.session_state: st.session_state[step_key] = 1
        
        if st.session_state[step_key] == 1:
            u_story = st.text_area(initial_prompt, height=120)
            if st.button(ui["btn_analyze"]):
                if u_story:
                    with st.spinner("Analyzing legal grounds..."):
                        q_prompt = f"ROLE: Legal Expert. TASK: {analyze_prompt_task} Context: '{u_story}'. CONSTRAINTS: Identify critical missing facts. OUTPUT: Ask strictly necessary investigative questions (minimum 1, maximum 5). Provide EACH question in BOTH English and Hindi (e.g., '1. [English]? / [Hindi]?')."
                        st.session_state[qs_key] = model.generate_content(q_prompt).text
                        st.session_state[story_key] = u_story
                        st.session_state[step_key] = 2
                        st.rerun()
        elif st.session_state[step_key] == 2:
            st.success(st.session_state[qs_key])
            u_answers = st.text_area("Provide Clarifications / स्पष्टीकरण दें:")
            
            doc_lang = st.radio("Select Output Language for Final Document / दस्तावेज़ की भाषा चुनें:", ["English", "Hindi"], horizontal=True, key=f"doc_{title}")
            
            col1, col2 = st.columns(2)
            with col1:
                if st.button(ui["btn_draft"]):
                    with st.spinner("Drafting document..."):
                        prompt = f"{draft_prompt_task} CONTEXT: Base Story: '{st.session_state[story_key]}'. Clarifications: '{u_answers}'. CONSTRAINTS: Be highly professional and legally accurate. OUTPUT: Format as a formal legal document in {doc_lang}."
                        st.write(model.generate_content(prompt).text + watermark)
            with col2:
                if st.button(ui["btn_reset"]): st.session_state[step_key] = 1; st.rerun()

    # --- ROUTING CITIZEN TOOLS ---
    if "FIR" in tool or "एफआईआर" in tool:
        interactive_tool(tool, "Draft a formal Police Complaint under the BNS 2023.", "Describe the incident roughly / घटना का विवरण दें:",
                         "Identify missing facts for a BNS 2023 FIR (time, weapons, witnesses).",
                         "ROLE: Elite Criminal Defense Counsel. TASK: Draft a formal FIR to the SHO. Apply BNS 2023.")
    
    elif "1930" in tool or "साइबर" in tool:
        interactive_tool(tool, "Draft a chronological complaint for the National Cyber Crime Reporting Portal (1930).", "How were you scammed? / आपके साथ धोखाधड़ी कैसे हुई?:",
                         "Identify missing financial facts (UTR numbers, transaction times, bank names, platform used).",
                         "ROLE: Cyber Law Expert. TASK: Draft a highly technical, chronological cyber fraud complaint for the NCCRP portal.")
    
    elif "Unfreeze" in tool or "अनफ्रीज" in tool:
        interactive_tool(tool, "Draft an application under Sec 457 CrPC / 503 BNSS to de-freeze a bank account.", "Why was your account frozen? / आपका खाता फ्रीज क्यों हुआ?:",
                         "Identify missing facts (date of freeze, bank name, investigating agency, transaction link).",
                         "ROLE: Criminal Trial Advocate. TASK: Draft an application to the Magistrate for de-freezing a bank account, asserting innocence in chain transactions.")
    
    elif "Rent" in tool or "किरायानामा" in tool:
        interactive_tool(tool, "Create a legally binding 11-month residential or commercial rent agreement.", "Provide Details (Names, Rent, Deposit) / विवरण दें:",
                         "Identify missing lease terms (address, lock-in period, notice period).",
                         "ROLE: Civil Real Estate Lawyer. TASK: Draft an 11-month Lease Agreement adhering to UP tenancy laws. Include lock-in and notice clauses.")
    
    elif "Eviction" in tool or "बेदखली" in tool:
        interactive_tool(tool, "Draft a strict 30-day statutory notice for a tenant to vacate premises.", "Why are you evicting them? / आप उन्हें बेदखल क्यों कर रहे हैं?:",
                         "Identify missing eviction grounds (months of default, specific damages, lease start date).",
                         "ROLE: Property Dispute Advocate. TASK: Draft a strict 30-day statutory eviction notice citing UP Rent Control laws.")
    
    elif "138" in tool or "बाउंस" in tool:
        interactive_tool(tool, "Generate a strict 15-day statutory legal notice for a dishonored cheque.", "Provide Cheque Details (Amount, Names) / चेक का विवरण दें:",
                         "Identify missing NI Act requirements (cheque date, return memo date, bounce reason).",
                         "ROLE: Corporate Litigator. TASK: Draft Sec 138 NI Act notice. Explicitly state the 15-day statutory warning for criminal proceedings.")
    
    elif "MSME" in tool:
        interactive_tool(tool, "Draft a strong payment recovery notice referencing the MSME Samadhaan provisions.", "Who owes you money? / आप पर किसका पैसा बकाया है?:",
                         "Identify missing MSME facts (Udyam Registration number, invoice dates, amount).",
                         "ROLE: Corporate Advocate. TASK: Draft MSME payment recovery notice invoking MSMED Act 2006 (compound interest). Strict 15-day deadline.")
    
    elif "Show Cause" in tool or "कारण बताओ" in tool:
        interactive_tool(tool, "Draft a respectful but legally defensive reply to a disciplinary notice.", "What are the charges against you? / आप पर क्या आरोप हैं?:",
                         "Identify missing disciplinary facts (date of notice, specific charges, user's defense).",
                         "ROLE: Service Law Advocate. TASK: Draft a formal reply to a Show Cause Notice. Tone should be respectful but invoke principles of natural justice.")
    
    elif "Traffic" in tool or "ट्रैफिक" in tool:
        interactive_tool(tool, "Generate an application to the Traffic Magistrate to request waiver of an e-challan.", "Provide challan details (Vehicle No., Offense) / चालान का विवरण दें:",
                         "Identify missing compounding facts (challan number, compelling reason/hardship for waiver).",
                         "ROLE: Traffic Court Advocate. TASK: Draft compounding/waiver application addressed to Traffic Magistrate/Lok Adalat.")

# ==========================================
# 6. LEGAL PROFESSIONAL TOOLS
# ==========================================
elif category == ui["tabs"][1]:
    desk = st.selectbox("Select Legal Desk:", ui["adv_desks"])
    tool = st.selectbox("Select Tool:", ui["adv_tools"][desk])

    def adv_interactive_tool(title, info_text, initial_prompt, analyze_prompt_task, draft_prompt_task):
        st.subheader(title)
        st.info(info_text, icon="ℹ️")
        
        step_key = f"adv_{title}_step"
        qs_key = f"adv_{title}_qs"
        story_key = f"adv_{title}_story"
        
        if step_key not in st.session_state: st.session_state[step_key] = 1
        
        if st.session_state[step_key] == 1:
            u_story = st.text_area(initial_prompt, height=120)
            if st.button(ui["btn_analyze"]):
                if u_story:
                    with st.spinner("Analyzing Legal Architecture..."):
                        q_prompt = f"ROLE: Senior Counsel. TASK: {analyze_prompt_task} Context: '{u_story}'. CONSTRAINTS: Identify missing legal grounds. OUTPUT: Ask (1 to 5) sharp questions. Provide EACH question in BOTH English and Hindi."
                        st.session_state[qs_key] = model.generate_content(q_prompt).text
                        st.session_state[story_key] = u_story
                        st.session_state[step_key] = 2
                        st.rerun()
        elif st.session_state[step_key] == 2:
            st.success(st.session_state[qs_key])
            u_answers = st.text_area("Your Answers:")
            doc_lang = st.radio("Select Output Language:", ["English", "Hindi"], horizontal=True, key=f"doc_{title}")
            
            col1, col2 = st.columns(2)
            with col1:
                if st.button(ui["btn_draft"]):
                    with st.spinner("Structuring Legal Draft..."):
                        prompt = f"{draft_prompt_task} CONTEXT: Base: '{st.session_state[story_key]}', Extra: '{u_answers}'. OUTPUT: Traditional court drafting format in {doc_lang}."
                        st.write(model.generate_content(prompt).text + watermark)
            with col2:
                if st.button(ui["btn_reset"]): st.session_state[step_key] = 1; st.rerun()

    # --- ROUTING ADVOCATE TOOLS ---
    if "Bail" in tool or "जमानत" in tool:
        adv_interactive_tool(tool, "Draft a comprehensive regular bail application under Section 483 of the BNSS.", "Provide basic FIR Details & Sections:",
                             "Identify missing bail grounds (date of arrest, applicant's specific role, parity).",
                             "ROLE: Top-tier Criminal Defense Advocate. TASK: Draft Regular Bail App under Sec 483 BNSS. Address to District & Sessions Judge. Argue the 'Triple Test'.")
    
    elif "Affidavit" in tool or "हलफनामा" in tool:
        adv_interactive_tool(tool, "Generate Counter-Affidavits adhering to the formatting of the Lucknow Bench.", "Provide Case Title and brief subject matter:",
                             "Identify missing facts for the affidavit (Deponent details, para-wise rebuttals).",
                             "ROLE: High Court Counsel. TASK: Draft Counter-Affidavit. Adhere strictly to archaic legal phrasing of the Allahabad High Court, Lucknow Bench. Use numbered paragraphs.")
    
    elif "Writ" in tool or "रिट" in tool:
        adv_interactive_tool(tool, "Draft specific constitutional grounds for a Writ Petition (Article 226) in Service/Administrative Matters.", "Provide details of the wrongful government action:",
                             "Identify missing constitutional grounds (fundamental rights breached, exact impugned order, malafide intent).",
                             "ROLE: High Court Counsel. TASK: Draft the 'Grounds' section for an Article 226 Writ Petition. Focus on arbitrary state action, violation of Article 14/16/21, and Wednesbury unreasonableness.")

    elif "Summarizer" in tool or "सारांश" in tool:
        st.subheader(tool)
        st.info("Extract the core Issue, Facts, Ratio Decidendi, and Precedents from lengthy judgments.", icon="ℹ️")
        judgment = st.text_area("Paste Judgment Text:", height=200)
        doc_lang = st.radio("Select Output Language:", ["English", "Hindi"], horizontal=True, key="doc_sum")
        if st.button("Generate Summary"):
            with st.spinner("Analyzing Ratio Decidendi..."):
                prompt = f"ROLE: Brilliant Judicial Clerk at Supreme Court. TASK: Deep legal analysis of judgment: '{judgment}'. CONSTRAINTS: Strip procedural fluff. Output strictly using 5 headers: 1. Core Legal Issue, 2. Material Facts, 3. Ratio Decidendi, 4. Key Precedents, 5. Final Verdict. OUTPUT: Professional legal brief in {doc_lang}."
                st.success(model.generate_content(prompt).text)

    elif "IPC" in tool:
        st.subheader(tool)
        st.info("Instantly map old Indian Penal Code (IPC) sections to the exact matching provisions of the new BNS 2023.", icon="ℹ️")
        sec = st.text_input("Enter IPC Section / Offense Name:")
        doc_lang = st.radio("Select Output Language:", ["English", "Hindi"], horizontal=True, key="doc_ipc")
        if st.button("Convert to BNS 2023"):
            prompt = f"ROLE: Indian Law Professor. TASK: Map IPC Section {sec} to the exact new BNS 2023 section. CONSTRAINTS: Be 100% accurate regarding the new statute. OUTPUT: Direct section mapping and a 2-line explanation in {doc_lang}."
            st.success(model.generate_content(prompt).text)

# ==========================================
# 7. PARTNER ADVOCATE PROGRAM
# ==========================================
elif category == ui["tabs"][2]:
    st.markdown("### 🤝 Grow Your Practice with NyayaSahayak")
    st.write("Join India's fastest-growing legal network. Receive verified, high-intent legal leads directly from citizens in your specific city and practice area.")
    st.info("Currently onboarding advocates for Tier-2 and Tier-3 cities in Uttar Pradesh. High Court matters remain exclusively handled by NyayaSahayak Central Chambers.")

    with st.form("partner_form", clear_on_submit=True):
        adv_name = st.text_input("Advocate Name:")
        adv_bar = st.text_input("Bar Council Enrollment Number (e.g., UP/XXXX/YYYY):")
        adv_city = st.text_input("City / District Court of Practice:")
        adv_phone = st.text_input("WhatsApp Number:")
        adv_category = st.multiselect("Preferred Lead Categories:", ["Criminal/Bail", "Cyber Crime & Fraud", "Property/Civil", "Cheque Bounce/MSME", "Service/Administrative", "Family/Divorce"])
        
        submitted_adv = st.form_submit_button("Apply to Join Network")
        if submitted_adv:
            if adv_name and adv_bar and adv_city:
                st.success(f"Application Submitted! Our team will verify your Bar ID ({adv_bar}) and contact you regarding lead distribution in {adv_city}.")
            else:
                st.error("Please fill in your Name, Bar Council Number, and City.")

st.divider()

# ==========================================
# 8. GLOBAL CRM & ADVANCED LEAD CAPTURE
# ==========================================
if category == ui["tabs"][0]:
    st.markdown("### 👨‍⚖️ Need Formal Representation?" if ui_lang == "English" else "### 👨‍⚖️ औपचारिक प्रतिनिधित्व की आवश्यकता है?")
    st.write("Drafts generated by AI are for reference only. For official court filing, tribunal representation, or case strategy, schedule a consultation." if ui_lang == "English" else "आधिकारिक कोर्ट फाइलिंग या केस रणनीति के लिए, हमारे मुख्य कानूनी सलाहकार के साथ परामर्श बुक करें।")

    with st.form("intake_form", clear_on_submit=True):
        client_name = st.text_input("Full Name / पूरा नाम:")
        client_phone = st.text_input("WhatsApp Number / संपर्क नंबर:")
        client_issue = st.selectbox("Matter Type / मामले का प्रकार:", ["Criminal Defense / Bail", "Cyber Fraud / Account Freeze", "Civil & Property Disputes", "Cheque Bounce & Commercial", "Service Matters / Government", "Family & Divorce", "Other"])
        
        # New Smart Lead Qualifier
        client_stage = st.selectbox("Current Stage of Matter / मामले की वर्तमान स्थिति:", [
            "Pre-litigation / Not yet filed", 
            "Police Station / Cyber Cell", 
            "District & Sessions Court", 
            "Tribunals (RERA, CAT, DRT, Consumer)", 
            "High Court"
        ])
        
        submitted = st.form_submit_button(ui["req"])
        if submitted:
            if client_name and client_phone:
                st.success(f"Request Received. Adv. Shobhit Tiwari's office will contact {client_name} at {client_phone} shortly." if ui_lang == "English" else f"अनुरोध प्राप्त हुआ। अधिवक्ता शोभित तिवारी का कार्यालय जल्द ही {client_phone} पर {client_name} से संपर्क करेगा।")
            else:
                st.error("Please provide both your name and contact number." if ui_lang == "English" else "कृपया अपना नाम और संपर्क नंबर दोनों प्रदान करें।")

# ==========================================
# 9. LOCAL SEO & LEGAL FOOTER
# ==========================================
st.divider()
st.markdown("""
<div style='text-align: justify; font-size: 11px; color: gray;'>
    <b>NyayaSahayak platform is intended for educational and preliminary drafting assistance. It does not establish an attorney-client relationship.</b><br><br>
    <b>Full-Service Litigation Chamber:</b> Representing clients in Criminal Defense, Cyber Law, Service Matters, Arbitration, and Property Disputes. Serving clients across Uttar Pradesh at the Allahabad High Court (Lucknow Bench), District & Sessions Courts, and Specialized Tribunals (CAT, RERA, DRT).<br>
    © 2026 NyayaSahayak. Chief Legal Advisor: Adv. Shobhit Tiwari.
</div>
""", unsafe_allow_html=True)
